name: Main workflow
on: push
jobs:
  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx markdown-cli *.md
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  sonarcloud:
    needs: [Build]
    name: SonarCloud Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUDTOKEN }}
  security:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: code        # 👈 гарантира, че ./code ще съществува
  
      - name: Preflight (see what we got)
        run: |
          pwd
          ls -la
          echo "---- ./code ----"
          ls -la code
  
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
  
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYKTOKEN }}
  
      - name: Snyk OSS (Gradle)
        run: snyk test --all-sub-projects --configuration-matching='^(?!test).*' --severity-threshold=high
        working-directory: code      # 👈 вече съществува
        env:
          SNYK_TOKEN: ${{ secrets.SNYKTOKEN }}


  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: run linting
        uses: super-linter/super-linter/slim@v7 
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
